Repository JuliaRobotics/AprilTags.jl, pull requests merged in 2021-01, with the labels that each got.

#68 test other os
  .travis.yml
  test/homography.jl
Labels: tests

#67 Update to use AprilTags_jll
  .codecov.yml
  .travis.yml
  Project.toml
  REQUIRE
  appveyor.yml
  deps/build.jl
  src/AprilTags.jl
  src/helpers.jl
  test/homography.jl
Labels: enhancement

#69 example written by @Affie, see #66
  docs/src/index.md
Labels: documentation, example, tests

#70 fix drawTagAxis! and swop cx,cy to close #66
  src/tagdraw.jl
  test/basictests.jl
Labels: bug fix

#74 mini update to calib in docs
  docs/src/index.md
  src/calibrationutils.jl
Labels: documentation, maintenance
